//! Versioned, transport-neutral event envelopes.
//!
//! Events carry minimal identifiers and metadata only — never full clinical
//! payloads or PHI in routing keys. Consumers fetch authorized data through
//! governed APIs.

use crate::ids::{CorrelationId, EventId, TenantId};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventEnvelope {
    pub event_id: EventId,
    /// e.g. "result.received"
    pub event_type: String,
    pub schema_version: String,
    pub tenant_id: TenantId,
    /// Regional cell identifier (development baseline: "cell-dev-1").
    pub cell: String,
    /// Human user or service principal that caused the event.
    pub actor: String,
    pub correlation_id: CorrelationId,
    pub causation_id: Option<EventId>,
    pub occurred_at: DateTime<Utc>,
    pub recorded_at: DateTime<Utc>,
    pub source: String,
    /// Minimal resource references (ids only, no clinical payloads).
    pub resource_refs: Value,
}

/// Event vocabulary implemented by the vertical slice.
pub const EVENT_TYPES: &[&str] = &[
    "patient.registered",
    "encounter.started",
    "encounter.cancelled",
    "encounter.note.saved",
    "encounter.note.signed",
    "encounter.note.addendum",
    "encounter.vitals.recorded",
    "encounter.diagnosis.added",
    "encounter.recording.consent_recorded",
    "encounter.scribe.transcribed",
    "encounter.scribe.applied",
    "encounter.scribe.dismissed",
    "visit.created",
    "visit.arrived",
    "visit.triage.saved",
    "visit.triage.completed",
    "visit.assigned",
    "visit.consultation.started",
    "visit.consultation.released",
    "visit.completed",
    "visit.cancelled",
    "visit.no_show",
    "internal_alert.created",
    "internal_alert.acknowledged",
    "internal_alert.resolved",
    "service_request.created",
    "result.received",
    "result.amended",
    "result.critical_flagged",
    "result.reviewed",
    "patient.notified",
    "follow_up.created",
    "follow_up.overdue",
    "result_loop.closed",
    "consent.changed",
    "policy.access_denied",
    "break_glass.activated",
    "break_glass.reviewed",
    "ai.artifact.requested",
    "ai.artifact.generated",
    "ai.artifact.reviewed",
    "ai.provider.unavailable",
    "ai.generation.failed",
    "risk.assessment.calculated",
    "risk.item.acknowledged",
    "risk.item.assigned",
    "risk.item.reviewed",
    "risk.suggestion.confirmed",
    "risk.projection.accessed",
    "catalog.entry.created",
    "catalog.entry.updated",
    "scheduling.policy.updated",
    "scheduling.facility.updated",
    "scheduling.calendar_event.recorded",
    "scheduling.calendar_event.deactivated",
    "scheduling.resource.created",
    "scheduling.resource.updated",
    "scheduling.resource.exception_recorded",
    "scheduling.resource.exception_removed",
    "scheduling.resource.availability_replaced",
    "scheduling.resource.deactivated",
    "catalog.entry.deactivated",
    "catalog.service_requirements.replaced",
    "access_request.created",
    "access_request.amended",
    "access_request.submitted",
    "access_request.triage_routed",
    "access_request.triage_cleared",
    "access_request.closed",
    "access_request.withdrawn",
    "access_request.transitioned",
    "access_request.matcher_run.read",
    "access_request.intent_interpreted",
    "access_request.matched",
    "appointment.offer.held",
    "appointment.offer.released",
    "appointment.offer.declined",
    "appointment.offer.expired",
    "appointment.offer.revoked",
    "appointment.offer.race_lost",
    "appointment.confirmed",
    "appointment.rescheduled",
    "appointment.cancelled",
    "appointment.fulfilled",
    "appointment.no_show",
    "appointment.patient_confirmed",
    "appointment.overridden",
    "appointment.transitioned",
    "appointment.reschedule_requested",
    "appointment.read",
    "appointment.ics.exported",
    "patient_grant.created",
    "patient_grant.revoked",
    "patient_calendar.connected",
    "patient_calendar.synchronized",
    "patient_calendar.disconnected",
    "waitlist.joined",
    "waitlist.paused",
    "waitlist.resumed",
    "waitlist.left",
    "waitlist.recovery.opened",
    "waitlist.recovery.offered",
    "waitlist.recovery.overridden",
    "waitlist.recovery.closed",
    "notification.scheduled",
    "notification.delivered",
    "notification.failed",
    "notification.dead_lettered",
    "notification.read",
    "capacity.forecast.calculated",
    "transport.requested",
    "transport.scheduled",
    "transport.status_changed",
    "transport.location.shared",
    "transport.location.read",
    "transport.address.read",
    "transport.location.purged",
];

pub fn is_known_event_type(t: &str) -> bool {
    EVENT_TYPES.contains(&t)
}
