//! Deterministic fake provider for local development and tests.
//!
//! Produces a stable, template-driven structured summary from the provided
//! facts with no network access. Can be switched into an "unavailable" mode
//! to exercise degradation paths.

use crate::{input_hash, GatewayError, GatewayResponse, ModelGateway, SummaryRequest};
use async_trait::async_trait;
use std::sync::atomic::{AtomicBool, Ordering};
use wellos_domain::ai::ResultSummaryV1;

#[derive(Default)]
pub struct FakeProvider {
    unavailable: AtomicBool,
}

impl FakeProvider {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn set_unavailable(&self, unavailable: bool) {
        self.unavailable.store(unavailable, Ordering::SeqCst);
    }
}

#[async_trait]
impl ModelGateway for FakeProvider {
    async fn summarize_result(
        &self,
        req: &SummaryRequest,
    ) -> Result<GatewayResponse, GatewayError> {
        if self.unavailable.load(Ordering::SeqCst) {
            return Err(GatewayError::Unavailable(
                "fake provider forced unavailable".into(),
            ));
        }
        let cited_sources: Vec<String> = req.facts.iter().map(|(r, _)| r.clone()).collect();
        let joined = req
            .facts
            .iter()
            .map(|(_, s)| s.as_str())
            .collect::<Vec<_>>()
            .join("; ");
        let (summary, limitation, steps) = if req.language == "es" {
            (
                format!("Resumen (borrador generado por IA, requiere revisión): {joined}"),
                "Generado por un proveedor determinista de desarrollo; no es una interpretación clínica.".to_string(),
                vec!["repetir-prueba".to_string(), "revisar-medicación".to_string(), "contactar-paciente".to_string()],
            )
        } else {
            (
                format!("Summary (AI-generated draft, requires review): {joined}"),
                "Generated by a deterministic development provider; not a clinical interpretation."
                    .to_string(),
                vec![
                    "repeat-test".to_string(),
                    "review-medications".to_string(),
                    "contact-patient".to_string(),
                ],
            )
        };
        Ok(GatewayResponse {
            output: ResultSummaryV1 {
                schema_version: "result-summary.v1".into(),
                summary,
                relevant_trend: None,
                cited_sources,
                limitations: vec![limitation],
                suggested_next_step_categories: steps,
            },
            model: "dmind-fake".into(),
            model_version: "0.1.0".into(),
            route: "local-fake".into(),
            input_hash: input_hash(req),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn req(lang: &str) -> SummaryRequest {
        SummaryRequest {
            template: "result-summary@1.0.0".into(),
            facts: vec![(
                "obs:1".into(),
                "Potassium 7.1 mmol/L (critical high)".into(),
            )],
            language: lang.into(),
        }
    }

    #[tokio::test]
    async fn deterministic_output_cites_sources() {
        let p = FakeProvider::new();
        let a = p.summarize_result(&req("en")).await.unwrap();
        let b = p.summarize_result(&req("en")).await.unwrap();
        assert_eq!(a.output.summary, b.output.summary);
        assert_eq!(a.input_hash, b.input_hash);
        assert_eq!(a.output.cited_sources, vec!["obs:1".to_string()]);
        assert!(!a.output.limitations.is_empty());
    }

    #[tokio::test]
    async fn unavailable_mode_returns_error() {
        let p = FakeProvider::new();
        p.set_unavailable(true);
        assert!(matches!(
            p.summarize_result(&req("en")).await,
            Err(GatewayError::Unavailable(_))
        ));
    }

    #[tokio::test]
    async fn spanish_output_is_localized() {
        let p = FakeProvider::new();
        let a = p.summarize_result(&req("es")).await.unwrap();
        assert!(a.output.summary.starts_with("Resumen"));
    }
}
